# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  DOS_Library_config = debug
  DOS_config = debug
endif
ifeq ($(config),release)
  DOS_Library_config = release
  DOS_config = release
endif
ifeq ($(config),dist)
  DOS_Library_config = dist
  DOS_config = dist
endif

PROJECTS := DOS-Library DOS

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

DOS-Library:
ifneq (,$(DOS_Library_config))
	@echo "==== Building DOS-Library ($(DOS_Library_config)) ===="
	@${MAKE} --no-print-directory -C App-Core -f Makefile config=$(DOS_Library_config)
endif

DOS: DOS-Library
ifneq (,$(DOS_config))
	@echo "==== Building DOS ($(DOS_config)) ===="
	@${MAKE} --no-print-directory -C App -f Makefile config=$(DOS_config)
endif

clean:
	@${MAKE} --no-print-directory -C App-Core -f Makefile clean
	@${MAKE} --no-print-directory -C App -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   DOS-Library"
	@echo "   DOS"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"